config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
  get '/search', to: 'search#search'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms


end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :book_edit_check,only: [:edit]

  def index
    @book = Book.new
    @user = User.find(current_user[:id])
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(book.id)
    else
      @user = User.find(current_user[:id])
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
    @new_book = Book.new

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      flash[:notice] = "You have updted book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def book_edit_check
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end


end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if  user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end


  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
  
  def about
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@records = User.search_for(@content, @method)
		else
			@records = Book.search_for(@content, @method)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find(current_user[:id])
    @users = User.all
    @book =Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
 <%= form_with model: book, local:true do |f| %>
        <div class="form-gruop">
          <%= f.label :title %></br>
          <%= f.text_field :title, autofocus: true, id:"book_title" %>
        </div>
        <div class="form-gruop">
          <%= f.label :opinion %></br>
          <%= f.text_area :body, autofocus: true, id:"book_body" %>
        </div>
        <%= f.submit %>
      <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this obj from being saved:</br>
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <p>
            <%= f.label :title %></br>
            <%= f.text_field :title, autofocus: true, id:"book_title" %>
          </p>
        </div>
        <div class="form-group">
          <p>
            <%= f.label :opinion %></br>
            <%= f.text_area :body, autofocus: true, id:"book_body" %>
          </p>
        </div>
        <%= f.submit %>
      <% end %>
      <p>
        <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:</br>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image_id, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %>
      <table>
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <p><%= link_to "", edit_user_path(@user), class: "btn btn-outline-socondary btn-block fas fa-user-cog edit_user_27083" %></p>
      </div>

      <h2>New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <label for="book_title">Title</label></br>
        <%= f.text_field :title, autofocus: true, id:"book_title" %>
        <p><label for="book_body">Opinion</label></br>
        <%= f.text_area :body, autofocus: true, id:"book_body" %></p>
        <%= f.submit %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image_id, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <p style="color:red" id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>

      <h2>New book</h2>
      <%= form_with model: @new_book, local:true do |f| %>
        <label for="book_title">Title</label></br>
        <%= f.text_field :title, autofocus: true, id:"book_title" %>
        <p><label for="book_body">Opinion</label></br>
        <%= f.text_area :body, autofocus: true, id:"book_body" %></p>
        <%= f.submit %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                  <%= attachment_image_tag @book.user, :profile_image_id, :fill, 50, 50, format: "jpeg", fallback: "no_image.jpg" %></br>
                  <%= @user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
                <td><%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
              <% end %>
              <td></td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/chats/crete.js.erb
$('.message').append("<p style='text-align: right;'><%= @chat.message %></p>");
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="message">
  <h1 id="room" data-room="<%= @room.id %>" data-user="<%= current_user.id %>"><%= @user.name %> さんとのチャット</h1>
  <% @chats.each do |chat| %>
    <% if chat.user_id == current_user.id %>
      <p style="text-align: right;"><%= chat.message %></p>
    <% else %>
      <p style="text-align: left;"><%= chat.message %></p>
    <% end %>
  <% end %>
  <%= form_with model: @chat do |f| %>
    <%= f.text_field :message %>
    <%= f.hidden_field :room_id %>
  <% end %>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcom to <i class="fas fa-book"></i>Bookers!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>
     <p style="color:red" id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

      <h1>welcom to , <i class="fas fa-book"></i> Bookers!!</h1>

      <p>In<i class="fas fa-book"></i><strong>Bookers,</strong><p>

      <p>you can sher and exchange your opinions, inpetion, and emotions</p>

      <p>about various books!<p>

      <p><%= link_to "Log In", new_user_session_path, class: "btn btn-info btn-sm btn-block " %></p>
      <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %></p>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2P</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>



                <li class="nav-item">
                  <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
                </li>

              <% else %>
                <li class="nav-item">
                  <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
                </li>
                <li class="nav-iem">
                  <%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="search-form text-right mt-1">
      <%= form_with url: search_search_path, method: :get, local: true do |f| %>
        <%= f.text_field :content %>
        <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
        <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
        <%= f.submit '検索' %>
      <% end %>
    </div>

    <main class="mb-auto">
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratot.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/search/search.html.erb
<% if @model == 'user' %>
	<h3>Users search for "<%= @content %>"</h3>
  <table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% elsif @model == 'book' %>
	<h3>Books search for "<%= @content %>"</h3>
  <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>

          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/users/_info.html.erb
<%= attachment_image_tag user, :profile_image_id, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %>
      <table>
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <% if current_user != user %>
        <%= link_to 'chatを始める', chat_path(user.id) %>
      <% end %>

      <div class="row">
        <p><%= link_to "", edit_user_path(user), class: "btn btn-outline-socondary btn-block fas fa-user-cog edit_user_27083" %></p>
      </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>

      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this obj from being saved:</br>
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>


      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <p>
            <%= f.label :name %></br>
            <%= f.text_field :name, autofocus: true, id:"user_name" %>
          </p>
        </div>
        <div class="form-group">
          <p>
            <%= f.label :Image %></br>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </p>
        </div>
        <div class="form-group">
          <p>
            <%= f.label :introduction %></br>
            <%= f.text_area :introduction, autofocus: true, id:"user_introduction" %>
          </p>
        </div>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "info", user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user.id) do %>
                  <%= attachment_image_tag user, :profile_image_id, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
     <p style="color:red" id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "info", user: @user %>

      <h2>New book</h2>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image_id, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>